version: 0.2

phases:
  install:
    commands:
      # Change directory to the project folder
      - cd vote
      # Install Python dependencies
      - pip install -r requirements.txt
      # Install Trivy for image scanning
      - curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
      - export PATH=$PATH:/root/.local/bin  # Add Trivy to the PATH
      # Install Bandit for static analysis
      - pip install bandit
      # Download and unzip SonarQube Scanner with corrected URL
      - curl -sSL https://binaries.sonarsource.com/Commercial/sonar-scanner-cli/sonar-scanner-4.6.2.2472-linux.zip -o sonar-scanner.zip
      - unzip sonar-scanner.zip -d /opt/sonar-scanner  # Unzip to /opt
      - export PATH=$PATH:/opt/sonar-scanner/sonar-scanner-4.6.2.2472-linux/bin  # Add sonar-scanner to the PATH

  pre_build:
    commands:
      # Run Bandit for Python code security checks
      - bandit -r my_python_app

  build:
    commands:
      # Run Trivy for container/image security scan
      - trivy fs . --exit-code 1 --severity HIGH,CRITICAL
      # Run tests (e.g., using pytest)
      - pytest

  post_build:
    commands:
      # Run SonarQube scanner
      - sonar-scanner -Dsonar.projectKey=my-python-app -Dsonar.host.url=http://3.92.68.102:9000 -Dsonar.login=squ_01e57532fb456d834eb594cdc93209e0b1798ad1

artifacts:
  files:
    - '**/*'  # Save all files from the current directory
  discard-paths: yes
  base-directory: .  # Set base directory to the current directory

cache:
  paths:
    - '/root/.cache/pip/**/*'
